### ISSUE TITLE
[Bug]: Region dropdown is not updated when deleting meetings

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#1150]
### What happened?

If you delete all the meetings in a particular region you should see that region disappear from the dropdown on your public meetings page, but that is not happening, and it appears there is no way to actually do that save one: export to CSV and reimport, selecting the "Delete all meetings" option

Having done a little research on this topic it seems we need to be updating the `count` field in the `wp_term_taxonomy` table and we are not. This count should reflect the number of published posts with that taxonomy

I believe this is one of the issues mentioned in https://github.com/code4recovery/12-step-meeting-list/discussions/1145

**Comment by kiyote33** [comment]
Fixed in 3.15

**Comment by joshreisner** [comment]
<img width="816" alt="Screenshot 2024-02-14 at 9 51 19 AM" src="https://github.com/code4recovery/12-step-meeting-list/assets/1551689/6b492e95-e378-47e8-9980-b4d086f23a59">

confirmed it's still an issue in 3.14.30

**Comment by kiyote33** [comment]
As part of the redesign of the redesign of the  redesign, the code for dropping regions got removed. I'll have to dig to see if I can find it.
